### PR TITLE
Use Cucumber multipart import for Cucumber execution results

### PR DESCRIPTION
**Pull request by csvtuda**
Addresses #83, #84, #85, #87, #118.

- [x] Add Cucumber multipart call in `after:run` hook
- [x] Access JSON report created by `cypress-cucumber-preprocessor`
- Handle types of runs
  - [x] Cypress only
  - [x] Cucumber only
  - [x] Cypress & Cucumber
- [x] Remove `jira.createTestIssues` #114 
- [x] Remove `xray.testType` #117 
- Handle `jira.testExecutionIssueKey`
  - [x] Xray Cloud
  - [x] Xray Server
- Handle `jira.testExecutionIssueDescription`
  - [x] Xray Cloud
  - [x] Xray Server
- Handle `jira.testExecutionIssueSummary`
  - [x] Xray Cloud
  - [x] Xray Server
- Handle `jira.testPlanIssueKey`
  - [x] Xray Cloud
  - [x] Xray Server
- Handle `xray.uploadScreenshots`
  - [x] Xray Cloud
  - [x] Xray Server

### CODE REVIEW

**Comment by alexviz7** [comment]
Hi, is this ready or still in review?

**Comment by csvtuda** [comment]
Hey, I'm currently still working on it. I might be able to release a new version this weekend.

It's working quite well already. I just need to weave the plugin's options into the new upload process in some way.

**Comment by csvtuda** [comment]
@alexviz7 There's unfortunately a little bit more work to do, because the Cucumber results import behaves differently compared to the native Cypress results upload regarding automatic test issue creation. I have started removing some options to make Cypress & Cucumber upload behaviour consistent across the board. Afterwards it should be good to go.

**Comment by csvtuda** [comment]
@alexviz7 FYI, I will release version 4.0.0 soon once #123 is merged.

**Pull request merged**
